[package]
name = "video-vaapi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
nix = { version = "0.29", features = ["ioctl", "fs"] }

media-core = { workspace = true }
codec-core = { workspace = true }
capability-core = { workspace = true }
video-core = { workspace = true }
video-backend-api.workspace = true
video-frame-contract.workspace = true
cros-codecs = { version = "0.0.6", features = ["vaapi", "backend"] }
gbm = { version = "0.15", features = ["drm-support"] }
gbm-sys = "0.3"

[dev-dependencies]
static_assertions = "1.1"
