[package]
name = "video-vaapi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
bytes.workspace = true
wgpu.workspace = true
ash = "0.38"
wgpu-types = "29"
nix = { version = "0.29", features = ["ioctl", "fs"] }

webm-demux = { path = "../webm-demux" }
video-core = { path = "../video-core" }
cros-codecs = { version = "0.0.6", features = ["vaapi", "backend"] }
gbm = { version = "0.15", features = ["drm-support"] }
gbm-sys = "0.3"
