[package]
name = "web-media-dash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bounded-xml-reader.workspace = true
bytes.workspace = true
dash-mpd-core.workspace = true
demux-api.workspace = true
media-core.workspace = true
source-core.workspace = true
thiserror.workspace = true
web-media-adaptive.workspace = true
web-media-transport-api.workspace = true

[dev-dependencies]
rustiplayer-config.workspace = true
symphonia-demux.workspace = true
web-media-core.workspace = true
