[package]
name = "fastiplayer-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "fastiplayer_settings"
path = "src/lib.rs"

[dependencies]
player-core.workspace = true
render-core.workspace = true
fastiplayer-config.workspace = true
settings-core.workspace = true
