[package]
name = "rustiplayer-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "rustiplayer_storage"
path = "src/lib.rs"

[dependencies]
directories.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
