[package]
name = "flv-demux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
codec-core.workspace = true
demux-api.workspace = true
media-core.workspace = true
source-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
