[package]
name = "audio-timestretch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
audio-core = { workspace = true }
thiserror = { workspace = true }
timestretch = "0.4"

[dev-dependencies]
anyhow = { workspace = true }
symphonia = { workspace = true }
