[package]
name = "demux-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
media-core.workspace = true
source-core.workspace = true
thiserror.workspace = true
tracing.workspace = true
