[package]
name = "playlist-discovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
media-core = { workspace = true }
source-core = { workspace = true }
symphonia-demux = { workspace = true }
thiserror = { workspace = true }
