//! Binding между neutral `settings-core` и пользовательским `AppConfig`.
//!
//! Crate не владеет renderer/player/media runtime. Он строит registry, валидирует
//! и сохраняет `AppConfig`, а также переводит diff в typed owner-level routes.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use player_core::{
    PlayerRuntimeSettingId, PlayerRuntimeSettingsUpdate, PlayerTickConfig, PlayerWorkerConfig,
};
use render_core::{
    ColorAdjustment, ColorPipelineSettings, HdrOutputMode, HdrToSdrSettings,
    HdrToneMappingOperator, RenderLiveSettings, RenderLiveSettingsUpdate, SwapchainTransferMode,
};
use rustiplayer_config::{
    AppConfig, HdrToSdrOperatorConfig, NetworkConfig, OpenGlesConfig, RenderProfile,
    ToneMappingMode as ConfigToneMappingMode, UiConfig, VulkanConfig, YoutubeConfig,
    save_validated_atomic_at,
};
use settings_core::{
    ApplyMechanism, ApplyRouteReport, ApplyRouteResult, CommittedApplyRequest,
    CommittedSettingsApplier, PersistReport, PersistRequest, RouteApplyUpdate, RouteGeneration,
    SettingApplyMode, SettingChange, SettingDescriptor, SettingId, SettingRouteId, SettingsDiff,
    SettingsError, SettingsPersister, SettingsRegistry, SettingsResult, SettingsSchema,
    SettingsValidator, ValidationReport, ValidationRequest,
};

/// Route id generated by `rustiplayer-config` metadata for UI-only settings.
pub const UI_ROUTE_ID: &str = "ui";

/// Route id generated by metadata for live-render preview settings.
pub const RENDER_PREVIEW_ROUTE_ID: &str = "render";

/// Route id generated by metadata for committed renderer lifecycle settings.
pub const RENDER_COMMITTED_ROUTE_ID: &str = "render";

/// Route id generated by metadata for player policy settings.
pub const PLAYER_ROUTE_ID: &str = "player";

/// Route id generated by metadata for audio settings owned through player/runtime.
pub const AUDIO_ROUTE_ID: &str = "audio";

/// Route id generated by metadata for video/player runtime settings.
pub const VIDEO_ROUTE_ID: &str = "video";

/// Route id generated by metadata for network/media-source settings.
pub const NETWORK_ROUTE_ID: &str = "network";

/// Route id generated by metadata for YouTube service settings.
pub const YOUTUBE_ROUTE_ID: &str = "youtube";

/// Returns the generated registry for the full user config document.
pub fn app_config_registry() -> SettingsResult<SettingsRegistry<AppConfig>> {
    AppConfig::settings_registry()
}

/// Full-document validator that delegates to the authoritative config layer.
#[derive(Debug, Clone, Copy, Default)]
pub struct AppConfigValidator;

impl SettingsValidator<AppConfig> for AppConfigValidator {
    fn validate(
        &mut self,
        request: ValidationRequest<'_, AppConfig>,
    ) -> SettingsResult<ValidationReport> {
        request
            .draft
            .validate()
            .map_err(settings_error_from_display)?;

        Ok(ValidationReport::valid(setting_ids_from_diff(
            request.changed_settings,
        )))
    }
}

/// Atomic TOML persister backed by `rustiplayer-config::save_validated_atomic_at`.
#[derive(Debug, Clone)]
pub struct AppConfigStore {
    path: PathBuf,
}

impl AppConfigStore {
    /// Creates a store for one concrete user config path.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    /// Returns the target TOML path used by this store.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }
}

impl SettingsPersister<AppConfig> for AppConfigStore {
    fn persist(&mut self, request: PersistRequest<'_, AppConfig>) -> SettingsResult<PersistReport> {
        // Важный invariant: этот метод не делает partial write сам; вся durability
        // политика остаётся внутри `rustiplayer-config`.
        save_validated_atomic_at(&self.path, request.document)
            .map_err(settings_error_from_display)?;

        Ok(PersistReport::persisted())
    }
}

/// Combined settings delegate used by future app-level runtime wiring.
pub struct AppConfigSettingsDelegate<A> {
    validator: AppConfigValidator,
    store: AppConfigStore,
    runtime_applier: A,
}

impl<A> AppConfigSettingsDelegate<A> {
    /// Creates a delegate that validates, persists and then calls a runtime applier.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>, runtime_applier: A) -> Self {
        Self {
            validator: AppConfigValidator,
            store: AppConfigStore::new(path),
            runtime_applier,
        }
    }

    /// Returns the concrete config path used by the persistence delegate.
    #[must_use]
    pub fn path(&self) -> &Path {
        self.store.path()
    }

    /// Returns the wrapped runtime applier.
    #[must_use]
    pub fn runtime_applier(&self) -> &A {
        &self.runtime_applier
    }

    /// Returns the wrapped runtime applier mutably.
    #[must_use]
    pub fn runtime_applier_mut(&mut self) -> &mut A {
        &mut self.runtime_applier
    }

    /// Consumes the delegate and returns the wrapped runtime applier.
    #[must_use]
    pub fn into_runtime_applier(self) -> A {
        self.runtime_applier
    }
}

impl<A> SettingsValidator<AppConfig> for AppConfigSettingsDelegate<A> {
    fn validate(
        &mut self,
        request: ValidationRequest<'_, AppConfig>,
    ) -> SettingsResult<ValidationReport> {
        self.validator.validate(request)
    }
}

impl<A> SettingsPersister<AppConfig> for AppConfigSettingsDelegate<A> {
    fn persist(&mut self, request: PersistRequest<'_, AppConfig>) -> SettingsResult<PersistReport> {
        self.store.persist(request)
    }
}

impl<A> CommittedSettingsApplier<AppConfig> for AppConfigSettingsDelegate<A>
where
    A: AppRuntimeRouteApplier,
{
    fn apply_committed(
        &mut self,
        request: CommittedApplyRequest<'_, AppConfig>,
    ) -> SettingsResult<Vec<ApplyRouteReport>> {
        let mut reports = Vec::with_capacity(request.route_updates.len());

        for update in request.route_updates {
            let routes = committed_routes_from_update(
                request.previous_committed,
                request.persisted,
                update,
            )?;
            for route in routes {
                let report = self.runtime_applier.apply_committed_route(route)?;
                reports.push(report.into_core_report());
            }
        }

        Ok(reports)
    }
}

/// Runtime owner route after metadata routes are mapped to project-level owners.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AppRuntimeRoute {
    /// UI shell/settings-runtime state.
    Ui,

    /// Live render route that may be previewed before persistence.
    RenderPreview,

    /// Committed renderer lifecycle/backend settings.
    RenderCommitted,

    /// Player worker/session/audio-runtime contract route.
    Player,

    /// Network/source/service policy route.
    MediaService,
}

/// Owner-defined atomic group inside a runtime route.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AppRuntimeRouteGroup {
    /// UI chrome state such as language, skin and telemetry visibility.
    UiShell,

    /// Settings-runtime controls, for example preview pacing.
    UiSettingsRuntime,

    /// Renderer color-adjustment group that can be previewed in-place.
    RenderColorAdjustment,

    /// Renderer HDR-to-SDR group that can be previewed in-place.
    RenderHdrToSdr,

    /// Renderer backend/profile lifecycle settings.
    RenderBackendLifecycle,

    /// Player tick/scheduler settings applied in-place by the worker.
    PlayerTickConfig,

    /// Default-volume policy for future media, not current playback volume.
    PlayerDefaultVolume,

    /// Selected audio output device policy for future audio outputs.
    PlayerAudioOutputDevice,

    /// Decoder/channel/pool settings that require controlled rebuild.
    PlayerDecoderThreadConfig,

    /// Video backend preference applied via app-owned pipeline rebuild.
    PlayerVideoBackend,

    /// Player/audio/video settings without an in-place S07 owner boundary.
    PlayerDeferredBoundary,

    /// Network/source cache and timeout policy.
    MediaNetwork,

    /// YouTube service policy.
    MediaYoutube,
}

/// Affected settings belonging to one owner-defined atomic group.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppRuntimeRouteGroupUpdate {
    /// Group id owned by the runtime route.
    pub group: AppRuntimeRouteGroup,

    /// Concrete setting ids that changed inside this group.
    pub affected_settings: Vec<SettingId>,
}

/// Preview route update produced from a settings diff.
#[derive(Debug, Clone, PartialEq)]
pub struct RuntimePreviewRoute {
    /// Typed owner route.
    pub route: AppRuntimeRoute,

    /// Concrete metadata route ids that contributed to this owner route.
    pub source_routes: Vec<SettingRouteId>,

    /// Concrete setting ids affected by this route.
    pub affected_settings: Vec<SettingId>,

    /// Owner-defined atomic groups.
    pub groups: Vec<AppRuntimeRouteGroupUpdate>,

    /// Typed preview update payload.
    pub update: RuntimePreviewUpdate,
}

/// Committed route update produced from a settings diff.
#[derive(Debug, Clone, PartialEq)]
pub struct RuntimeCommittedRoute {
    /// Typed owner route.
    pub route: AppRuntimeRoute,

    /// Concrete metadata route ids that contributed to this owner route.
    pub source_routes: Vec<SettingRouteId>,

    /// Concrete setting ids affected by this route.
    pub affected_settings: Vec<SettingId>,

    /// Owner-defined atomic groups.
    pub groups: Vec<AppRuntimeRouteGroupUpdate>,

    /// Typed committed update payload.
    pub update: RuntimeCommittedUpdate,
}

/// Full route plan for one diff between two config documents.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct RuntimeRoutePlan {
    /// Routes that can be sent through preview apply.
    pub preview_routes: Vec<RuntimePreviewRoute>,

    /// Routes that must be applied after validation and persistence.
    pub committed_routes: Vec<RuntimeCommittedRoute>,
}

/// Typed preview payloads.
#[derive(Debug, Clone, PartialEq)]
pub enum RuntimePreviewUpdate {
    /// Renderer-neutral live settings update.
    Render(RenderPreviewSettingsUpdate),
}

/// Typed committed payloads.
#[derive(Debug, Clone, PartialEq)]
pub enum RuntimeCommittedUpdate {
    /// UI shell/settings-runtime update.
    Ui(UiRuntimeSettingsUpdate),

    /// Committed render live-settings route, usually preview promotion or retry.
    RenderPreview(RenderPreviewSettingsUpdate),

    /// Renderer lifecycle/backend update.
    RenderCommitted(RenderCommittedSettingsUpdate),

    /// Player worker/session/audio-runtime update.
    Player(Box<PlayerCommittedSettingsUpdate>),

    /// Network/source/service policy update.
    MediaService(MediaServiceRuntimeSettingsUpdate),
}

/// UI settings snapshot for app-level runtime owner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiRuntimeSettingsUpdate {
    /// Latest UI config snapshot.
    pub ui: UiConfig,
}

/// Renderer live settings payload plus render-core field-level diff.
#[derive(Debug, Clone, PartialEq)]
pub struct RenderPreviewSettingsUpdate {
    /// Neutral render update sent to `RenderLiveSettingsAdapter`.
    pub live_settings: RenderLiveSettingsUpdate,
}

/// Renderer committed lifecycle payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderCommittedSettingsUpdate {
    /// Renderer profile selection.
    pub profile: RenderProfile,

    /// Compatibility committed tone-mapping config.
    pub tone_mapping: ConfigToneMappingMode,

    /// Vulkan-specific committed settings.
    pub vulkan: VulkanConfig,

    /// OpenGL ES fallback committed settings.
    pub opengles: OpenGlesConfig,
}

/// Player route payload: player-core update plus settings not yet covered there.
#[derive(Debug, Clone, PartialEq)]
pub struct PlayerCommittedSettingsUpdate {
    /// Typed player-core update for supported runtime groups.
    pub player_core: PlayerRuntimeSettingsUpdate,

    /// Stable audio output device id selected through the audio owner boundary.
    pub audio_output_device_id: Option<String>,

    /// Settings in this route without a concrete S07 player-core update group.
    pub deferred_boundary_settings: Vec<SettingId>,
}

/// Media/service route payload without concrete service crate dependencies.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MediaServiceRuntimeSettingsUpdate {
    /// Network/source policy snapshot.
    pub network: NetworkConfig,

    /// YouTube service policy snapshot.
    pub youtube: YoutubeConfig,
}

/// Runtime route applier implemented by app-level composition code.
pub trait AppRuntimeRouteApplier {
    /// Applies one typed committed route and returns a detailed route report.
    fn apply_committed_route(
        &mut self,
        route: RuntimeCommittedRoute,
    ) -> SettingsResult<AppRouteApplyReport>;
}

/// Project-specific route result. Technical debt is explicit and never success.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppRouteApplyResult {
    /// Route fully applied the update.
    Applied,

    /// Route was already in the requested state.
    Noop,

    /// Previously active preview became committed state.
    PreviewPromoted,

    /// Only part of the route applied.
    PartialFailure { message: String },

    /// Route failed before applying the requested update.
    Failed { message: String },

    /// Route generation conflict blocked apply.
    Conflict {
        /// Generation captured by the editing transaction.
        baseline: RouteGeneration,

        /// Current generation seen before apply.
        current: RouteGeneration,
    },

    /// Honest marker for missing owner boundary; converted to a failed core report.
    DeferredTechnicalDebt { message: String },
}

impl AppRouteApplyResult {
    /// Returns true only for states that mean runtime reached the requested state.
    #[must_use]
    pub const fn is_success(&self) -> bool {
        matches!(self, Self::Applied | Self::Noop | Self::PreviewPromoted)
    }
}

/// Per-group route report for changed/skipped/failed/conflicted settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppRouteGroupReport {
    /// Owner-defined atomic group.
    pub group: AppRuntimeRouteGroup,

    /// Result for this group.
    pub result: AppRouteApplyResult,

    /// Concrete setting ids affected by this group.
    pub affected_settings: Vec<SettingId>,
}

/// Project-specific route report that preserves group-level details.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppRouteApplyReport {
    /// Typed owner route.
    pub route: AppRuntimeRoute,

    /// Concrete metadata routes that contributed to this owner route.
    pub source_routes: Vec<SettingRouteId>,

    /// Route-level result.
    pub result: AppRouteApplyResult,

    /// Runtime mechanism used by the owner.
    pub mechanism: ApplyMechanism,

    /// Concrete setting ids affected by this route.
    pub affected_settings: Vec<SettingId>,

    /// Owner-defined group details.
    pub groups: Vec<AppRouteGroupReport>,
}

impl AppRouteApplyReport {
    /// Converts to the neutral `settings-core` report expected by the controller.
    #[must_use]
    pub fn into_core_report(self) -> ApplyRouteReport {
        let route_id = self
            .source_routes
            .first()
            .cloned()
            .unwrap_or_else(|| route_id_for_runtime_route(self.route));
        let result = match self.result {
            AppRouteApplyResult::Applied => ApplyRouteResult::Applied,
            AppRouteApplyResult::Noop => ApplyRouteResult::Noop,
            AppRouteApplyResult::PreviewPromoted => ApplyRouteResult::PreviewPromoted,
            AppRouteApplyResult::PartialFailure { message } => {
                ApplyRouteResult::PartialFailure { message }
            }
            AppRouteApplyResult::Failed { message } => ApplyRouteResult::Failed { message },
            AppRouteApplyResult::Conflict { baseline, current } => {
                ApplyRouteResult::Conflict { baseline, current }
            }
            AppRouteApplyResult::DeferredTechnicalDebt { message } => {
                ApplyRouteResult::Failed { message }
            }
        };

        ApplyRouteReport {
            route: route_id,
            result,
            mechanism: self.mechanism,
            affected_settings: self.affected_settings,
        }
    }
}

/// Builds renderer-neutral live settings from a validated app config snapshot.
pub fn render_live_settings_from_config(config: &AppConfig) -> SettingsResult<RenderLiveSettings> {
    Ok(RenderLiveSettings {
        color_pipeline: color_pipeline_settings_from_config(config)?,
        hdr_to_sdr: hdr_to_sdr_settings_from_config(config),
        shader_parameters: Default::default(),
    })
}

/// Builds a full typed route plan from a registry diff.
pub fn runtime_route_plan_from_diff(
    registry: &SettingsRegistry<AppConfig>,
    previous: &AppConfig,
    current: &AppConfig,
    diff: &SettingsDiff,
) -> SettingsResult<RuntimeRoutePlan> {
    let mut route_inputs: BTreeMap<AppRuntimeRoute, RouteInput> = BTreeMap::new();

    for change in diff.changes() {
        let descriptor =
            registry
                .descriptor(&change.id)
                .ok_or_else(|| SettingsError::UnknownSetting {
                    id: change.id.clone(),
                })?;
        let route = runtime_route_from_descriptor(descriptor)?;
        route_inputs
            .entry(route)
            .or_insert_with(|| RouteInput::new(route))
            .push_change(change, descriptor.route.clone());
    }

    let mut plan = RuntimeRoutePlan::default();
    for input in route_inputs.into_values() {
        match input.route {
            AppRuntimeRoute::RenderPreview => {
                plan.preview_routes
                    .push(render_preview_route(previous, current, input.clone())?);
                plan.committed_routes
                    .push(render_preview_committed_route(previous, current, input)?);
            }
            AppRuntimeRoute::Ui => plan
                .committed_routes
                .push(ui_committed_route(current, input)),
            AppRuntimeRoute::RenderCommitted => plan
                .committed_routes
                .push(render_committed_route(current, input)),
            AppRuntimeRoute::Player => plan
                .committed_routes
                .push(player_committed_route(current, input)),
            AppRuntimeRoute::MediaService => plan
                .committed_routes
                .push(media_service_committed_route(current, input)),
        }
    }

    Ok(plan)
}

/// Builds committed routes from one controller route update.
///
/// Русский комментарий: `settings-derive` хранит route owner отдельно от
/// `apply_mode`, поэтому один metadata route вроде `render` может содержать и
/// preview, и committed settings. Здесь мы снова split-им его по setting id.
pub fn committed_routes_from_update(
    previous: &AppConfig,
    current: &AppConfig,
    update: &RouteApplyUpdate,
) -> SettingsResult<Vec<RuntimeCommittedRoute>> {
    let mut route_inputs: BTreeMap<AppRuntimeRoute, RouteInput> = BTreeMap::new();

    for setting_id in &update.affected_settings {
        let route = runtime_route_from_update_setting(&update.route, setting_id.as_str())?;
        route_inputs
            .entry(route)
            .or_insert_with(|| RouteInput::new(route))
            .push_setting_id(setting_id.clone(), update.route.clone());
    }

    let mut routes = Vec::new();
    for input in route_inputs.into_values() {
        let route = match input.route {
            AppRuntimeRoute::Ui => ui_committed_route(current, input),
            AppRuntimeRoute::RenderPreview => {
                render_preview_committed_route(previous, current, input)?
            }
            AppRuntimeRoute::RenderCommitted => render_committed_route(current, input),
            AppRuntimeRoute::Player => player_committed_route(current, input),
            AppRuntimeRoute::MediaService => media_service_committed_route(current, input),
        };
        routes.push(route);
    }

    Ok(routes)
}

fn hdr_to_sdr_settings_from_config(config: &AppConfig) -> HdrToSdrSettings {
    let hdr_to_sdr = &config.render.hdr_to_sdr;

    HdrToSdrSettings {
        enabled: hdr_to_sdr.enabled,
        operator: hdr_to_sdr_operator_from_config(hdr_to_sdr.operator),
        output_mode: HdrOutputMode::SdrBt709Only,
        sdr_reference_white_nits: hdr_to_sdr.sdr_reference_white_nits,
        hdr_reference_peak_nits: hdr_to_sdr.hdr_reference_peak_nits,
    }
}

const fn hdr_to_sdr_operator_from_config(
    operator: HdrToSdrOperatorConfig,
) -> HdrToneMappingOperator {
    match operator {
        HdrToSdrOperatorConfig::Bt2446C => HdrToneMappingOperator::Bt2446C,
    }
}

fn color_pipeline_settings_from_config(
    config: &AppConfig,
) -> SettingsResult<ColorPipelineSettings> {
    let color_adjustment = &config.render.color_adjustment;

    Ok(ColorPipelineSettings {
        adjustment: ColorAdjustment {
            brightness: color_adjustment.brightness,
            contrast: color_adjustment.contrast,
            saturation: color_adjustment.saturation,
            exposure: color_adjustment.exposure,
            rgb_gain: rgb_triplet_from_config(
                "render.color_adjustment.rgb_gain",
                &color_adjustment.rgb_gain,
            )?,
            rgb_offset: rgb_triplet_from_config(
                "render.color_adjustment.rgb_offset",
                &color_adjustment.rgb_offset,
            )?,
        },
        tone_mapping: render_core::ToneMappingMode::Off,
        swapchain_transfer: SwapchainTransferMode::PreserveCurrentUnorm,
    })
}

fn rgb_triplet_from_config(field: &'static str, values: &[f32]) -> SettingsResult<[f32; 3]> {
    if values.len() != 3 {
        return Err(SettingsError::access_failed(format!(
            "{field} должен содержать ровно 3 значения, получено {}",
            values.len()
        )));
    }

    for (channel_index, channel_value) in values.iter().copied().enumerate() {
        if !channel_value.is_finite() {
            return Err(SettingsError::access_failed(format!(
                "{field}[{channel_index}] должен быть конечным числом, получено {channel_value}"
            )));
        }
    }

    Ok([values[0], values[1], values[2]])
}

#[derive(Debug, Clone)]
struct RouteInput {
    route: AppRuntimeRoute,
    source_routes: Vec<SettingRouteId>,
    affected_settings: Vec<SettingId>,
}

impl RouteInput {
    fn new(route: AppRuntimeRoute) -> Self {
        Self {
            route,
            source_routes: Vec::new(),
            affected_settings: Vec::new(),
        }
    }

    fn push_change(&mut self, change: &SettingChange, source_route: SettingRouteId) {
        self.push_setting_id(change.id.clone(), source_route);
    }

    fn push_setting_id(&mut self, setting_id: SettingId, source_route: SettingRouteId) {
        push_unique_setting_route(&mut self.source_routes, source_route);
        push_unique_setting_id(&mut self.affected_settings, setting_id);
    }

    fn groups(&self) -> Vec<AppRuntimeRouteGroupUpdate> {
        groups_for_settings(self.route, &self.affected_settings)
    }
}

fn render_preview_route(
    previous: &AppConfig,
    current: &AppConfig,
    input: RouteInput,
) -> SettingsResult<RuntimePreviewRoute> {
    let previous_settings = render_live_settings_from_config(previous)?;
    let current_settings = render_live_settings_from_config(current)?;
    let update = RenderLiveSettingsUpdate::from_baseline(&previous_settings, current_settings);
    let groups = input.groups();

    Ok(RuntimePreviewRoute {
        route: AppRuntimeRoute::RenderPreview,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimePreviewUpdate::Render(RenderPreviewSettingsUpdate {
            live_settings: update,
        }),
    })
}

fn render_preview_committed_route(
    previous: &AppConfig,
    current: &AppConfig,
    input: RouteInput,
) -> SettingsResult<RuntimeCommittedRoute> {
    let previous_settings = render_live_settings_from_config(previous)?;
    let current_settings = render_live_settings_from_config(current)?;
    let update = RenderLiveSettingsUpdate::from_baseline(&previous_settings, current_settings);
    let groups = input.groups();

    Ok(RuntimeCommittedRoute {
        route: AppRuntimeRoute::RenderPreview,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::RenderPreview(RenderPreviewSettingsUpdate {
            live_settings: update,
        }),
    })
}

fn ui_committed_route(current: &AppConfig, input: RouteInput) -> RuntimeCommittedRoute {
    let groups = input.groups();

    RuntimeCommittedRoute {
        route: AppRuntimeRoute::Ui,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::Ui(UiRuntimeSettingsUpdate {
            ui: current.ui.clone(),
        }),
    }
}

fn render_committed_route(current: &AppConfig, input: RouteInput) -> RuntimeCommittedRoute {
    let groups = input.groups();

    RuntimeCommittedRoute {
        route: AppRuntimeRoute::RenderCommitted,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::RenderCommitted(RenderCommittedSettingsUpdate {
            profile: current.render.profile,
            tone_mapping: current.render.tone_mapping,
            vulkan: current.render.vulkan.clone(),
            opengles: current.render.opengles.clone(),
        }),
    }
}

fn player_committed_route(current: &AppConfig, input: RouteInput) -> RuntimeCommittedRoute {
    let groups = input.groups();
    let update = player_update_from_settings(current, &input.affected_settings);

    RuntimeCommittedRoute {
        route: AppRuntimeRoute::Player,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::Player(Box::new(update)),
    }
}

fn media_service_committed_route(current: &AppConfig, input: RouteInput) -> RuntimeCommittedRoute {
    let groups = input.groups();

    RuntimeCommittedRoute {
        route: AppRuntimeRoute::MediaService,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::MediaService(MediaServiceRuntimeSettingsUpdate {
            network: current.network.clone(),
            youtube: current.youtube.clone(),
        }),
    }
}

fn player_update_from_settings(
    current: &AppConfig,
    affected_settings: &[SettingId],
) -> PlayerCommittedSettingsUpdate {
    let mut player_core = PlayerRuntimeSettingsUpdate::empty();
    let mut tick_settings = Vec::new();
    let mut decoder_settings = Vec::new();
    let mut deferred_settings = Vec::new();
    let mut default_volume_changed = false;
    let mut audio_output_device_changed = false;
    let mut video_backend_changed = false;

    for setting_id in affected_settings {
        let setting_name = setting_id.as_str();
        if setting_name == "audio.output_device" {
            audio_output_device_changed = true;
            continue;
        }
        if setting_name == "video.preferred_backend" {
            video_backend_changed = true;
            continue;
        }

        match player_runtime_setting_id(setting_name) {
            Some(PlayerRuntimeSettingId::AudioDefaultVolume) => {
                default_volume_changed = true;
            }
            Some(runtime_id) if player_decoder_ready_queue_setting(setting_name) => {
                tick_settings.push(runtime_id);
                decoder_settings.push(runtime_id);
            }
            Some(runtime_id) if player_tick_setting(setting_name) => {
                tick_settings.push(runtime_id);
            }
            Some(runtime_id) if player_decoder_thread_setting(setting_name) => {
                decoder_settings.push(runtime_id);
            }
            Some(runtime_id) => {
                player_core = player_core.with_unsupported_settings([runtime_id]);
                deferred_settings.push(setting_id.clone());
            }
            None => deferred_settings.push(setting_id.clone()),
        }
    }

    if !tick_settings.is_empty() {
        player_core = player_core.with_tick_config(PlayerTickConfig::from(current), tick_settings);
    }
    if default_volume_changed {
        player_core = player_core.with_default_volume(
            current.audio.volume as f32,
            [PlayerRuntimeSettingId::AudioDefaultVolume],
        );
    }
    if !decoder_settings.is_empty() {
        player_core = player_core.with_decoder_thread_config(
            PlayerWorkerConfig::decoder_thread_config_from_app_config(current),
            decoder_settings,
        );
    }
    if video_backend_changed {
        player_core = player_core.with_video_backend([PlayerRuntimeSettingId::VideoPreferredBackend]);
    }

    PlayerCommittedSettingsUpdate {
        player_core,
        audio_output_device_id: audio_output_device_changed
            .then(|| current.audio.output_device.clone()),
        deferred_boundary_settings: deferred_settings,
    }
}

fn runtime_route_from_descriptor(
    descriptor: &SettingDescriptor,
) -> SettingsResult<AppRuntimeRoute> {
    runtime_route_from_metadata(
        &descriptor.route,
        descriptor.id.as_str(),
        descriptor.apply_mode,
    )
}

fn runtime_route_from_update_setting(
    route: &SettingRouteId,
    setting_id: &str,
) -> SettingsResult<AppRuntimeRoute> {
    let apply_mode = if render_preview_setting(setting_id) {
        SettingApplyMode::ImmediatePreview
    } else {
        SettingApplyMode::CommittedApply
    };

    runtime_route_from_metadata(route, setting_id, apply_mode)
}

fn runtime_route_from_metadata(
    route: &SettingRouteId,
    setting_id: &str,
    apply_mode: SettingApplyMode,
) -> SettingsResult<AppRuntimeRoute> {
    match (route.as_str(), apply_mode) {
        (UI_ROUTE_ID, _) => Ok(AppRuntimeRoute::Ui),
        (RENDER_PREVIEW_ROUTE_ID, SettingApplyMode::ImmediatePreview) => {
            Ok(AppRuntimeRoute::RenderPreview)
        }
        (RENDER_COMMITTED_ROUTE_ID, SettingApplyMode::CommittedApply) => {
            Ok(AppRuntimeRoute::RenderCommitted)
        }
        (PLAYER_ROUTE_ID | AUDIO_ROUTE_ID | VIDEO_ROUTE_ID, _) => Ok(AppRuntimeRoute::Player),
        (NETWORK_ROUTE_ID | YOUTUBE_ROUTE_ID, _) => Ok(AppRuntimeRoute::MediaService),
        (other, _) => Err(SettingsError::access_failed(format!(
            "unknown AppConfig settings route `{other}` for setting `{setting_id}`"
        ))),
    }
}

fn route_id_for_runtime_route(route: AppRuntimeRoute) -> SettingRouteId {
    match route {
        AppRuntimeRoute::Ui => SettingRouteId::from(UI_ROUTE_ID),
        AppRuntimeRoute::RenderPreview => SettingRouteId::from(RENDER_PREVIEW_ROUTE_ID),
        AppRuntimeRoute::RenderCommitted => SettingRouteId::from(RENDER_COMMITTED_ROUTE_ID),
        AppRuntimeRoute::Player => SettingRouteId::from(PLAYER_ROUTE_ID),
        AppRuntimeRoute::MediaService => SettingRouteId::from(NETWORK_ROUTE_ID),
    }
}

fn groups_for_settings(
    route: AppRuntimeRoute,
    affected_settings: &[SettingId],
) -> Vec<AppRuntimeRouteGroupUpdate> {
    let mut groups: BTreeMap<AppRuntimeRouteGroup, Vec<SettingId>> = BTreeMap::new();
    for setting_id in affected_settings {
        groups
            .entry(group_for_setting(route, setting_id.as_str()))
            .or_default()
            .push(setting_id.clone());
    }

    groups
        .into_iter()
        .map(|(group, affected_settings)| AppRuntimeRouteGroupUpdate {
            group,
            affected_settings,
        })
        .collect()
}

fn group_for_setting(route: AppRuntimeRoute, setting_id: &str) -> AppRuntimeRouteGroup {
    match route {
        AppRuntimeRoute::Ui if setting_id.starts_with("ui.settings.") => {
            AppRuntimeRouteGroup::UiSettingsRuntime
        }
        AppRuntimeRoute::Ui => AppRuntimeRouteGroup::UiShell,
        AppRuntimeRoute::RenderPreview if setting_id.starts_with("render.hdr_to_sdr.") => {
            AppRuntimeRouteGroup::RenderHdrToSdr
        }
        AppRuntimeRoute::RenderPreview => AppRuntimeRouteGroup::RenderColorAdjustment,
        AppRuntimeRoute::RenderCommitted => AppRuntimeRouteGroup::RenderBackendLifecycle,
        AppRuntimeRoute::Player if setting_id == "audio.volume" => {
            AppRuntimeRouteGroup::PlayerDefaultVolume
        }
        AppRuntimeRoute::Player if setting_id == "audio.output_device" => {
            AppRuntimeRouteGroup::PlayerAudioOutputDevice
        }
        AppRuntimeRoute::Player if player_tick_setting(setting_id) => {
            AppRuntimeRouteGroup::PlayerTickConfig
        }
        AppRuntimeRoute::Player if player_decoder_thread_setting(setting_id) => {
            AppRuntimeRouteGroup::PlayerDecoderThreadConfig
        }
        AppRuntimeRoute::Player if setting_id == "video.preferred_backend" => {
            AppRuntimeRouteGroup::PlayerVideoBackend
        }
        AppRuntimeRoute::Player => AppRuntimeRouteGroup::PlayerDeferredBoundary,
        AppRuntimeRoute::MediaService if setting_id.starts_with("youtube.") => {
            AppRuntimeRouteGroup::MediaYoutube
        }
        AppRuntimeRoute::MediaService => AppRuntimeRouteGroup::MediaNetwork,
    }
}

fn player_tick_setting(setting_id: &str) -> bool {
    matches!(
        setting_id,
        "audio.buffer_target_ms"
            | "player.seek.commit_timeout_ms"
            | "player.seek.resume_audio_min_buffer_ms"
            | "player.seek.resume_audio_gate_timeout_ms"
            | "player.seek.resume_video_min_ready_frames"
            | "player.seek.fast_preroll_budget_ms"
            | "player.seek.fast_preroll_video_packet_burst"
            | "video.max_decode_ahead_ms"
            | "video.present_queue_frames"
            | "video.scheduler.demux_packets_per_tick"
            | "video.scheduler.video_packets_per_tick"
            | "video.scheduler.decoded_frames_per_tick"
            | "video.scheduler.catch_up_budget_ms"
            | "video.scheduler.present_queue_min_frames"
            | "video.scheduler.present_queue_target_frames"
            | "video.scheduler.decode_ahead_target_ms"
            | "video.scheduler.surface_free_slots_min"
            | "video.scheduler.surface_free_slots_target"
    )
}

fn player_decoder_ready_queue_setting(setting_id: &str) -> bool {
    setting_id == "video.decoder_ready_queue_frames"
}

fn player_decoder_thread_setting(setting_id: &str) -> bool {
    matches!(
        setting_id,
        "video.decoder_packet_channel_frames"
            | "video.decoder_frame_channel_frames"
            | "video.decoder_ready_queue_frames"
            | "video.decoder_surface_pool_frames"
            | "video.zero_copy_surface_pool_slots"
    )
}

fn render_preview_setting(setting_id: &str) -> bool {
    setting_id.starts_with("render.color_adjustment.")
        || setting_id.starts_with("render.hdr_to_sdr.")
}

fn player_runtime_setting_id(setting_id: &str) -> Option<PlayerRuntimeSettingId> {
    let runtime_id = match setting_id {
        "audio.volume" => PlayerRuntimeSettingId::AudioDefaultVolume,
        "audio.buffer_target_ms" => PlayerRuntimeSettingId::AudioBufferTargetMs,
        "player.demux.max_consecutive_corrupted_packets" => {
            PlayerRuntimeSettingId::PlayerDemuxMaxConsecutiveCorruptedPackets
        }
        "player.preferred_video_codec_order" => {
            PlayerRuntimeSettingId::PlayerPreferredVideoCodecOrder
        }
        "player.seek.commit_timeout_ms" => PlayerRuntimeSettingId::PlayerSeekCommitTimeoutMs,
        "player.seek.resume_audio_min_buffer_ms" => {
            PlayerRuntimeSettingId::PlayerSeekResumeAudioMinBufferMs
        }
        "player.seek.resume_audio_gate_timeout_ms" => {
            PlayerRuntimeSettingId::PlayerSeekResumeAudioGateTimeoutMs
        }
        "player.seek.resume_video_min_ready_frames" => {
            PlayerRuntimeSettingId::PlayerSeekResumeVideoMinReadyFrames
        }
        "player.seek.fast_preroll_budget_ms" => {
            PlayerRuntimeSettingId::PlayerSeekFastPrerollBudgetMs
        }
        "player.seek.fast_preroll_video_packet_burst" => {
            PlayerRuntimeSettingId::PlayerSeekFastPrerollVideoPacketBurst
        }
        "video.max_decode_ahead_ms" => PlayerRuntimeSettingId::VideoMaxDecodeAheadMs,
        "video.present_queue_frames" => PlayerRuntimeSettingId::VideoPresentQueueFrames,
        "video.decoder_packet_channel_frames" => {
            PlayerRuntimeSettingId::VideoDecoderPacketChannelFrames
        }
        "video.decoder_frame_channel_frames" => {
            PlayerRuntimeSettingId::VideoDecoderFrameChannelFrames
        }
        "video.decoder_ready_queue_frames" => PlayerRuntimeSettingId::VideoDecoderReadyQueueFrames,
        "video.decoder_surface_pool_frames" => {
            PlayerRuntimeSettingId::VideoDecoderSurfacePoolFrames
        }
        "video.zero_copy_surface_pool_slots" => {
            PlayerRuntimeSettingId::VideoZeroCopySurfacePoolSlots
        }
        "video.scheduler.demux_packets_per_tick" => {
            PlayerRuntimeSettingId::VideoSchedulerDemuxPacketsPerTick
        }
        "video.scheduler.video_packets_per_tick" => {
            PlayerRuntimeSettingId::VideoSchedulerVideoPacketsPerTick
        }
        "video.scheduler.decoded_frames_per_tick" => {
            PlayerRuntimeSettingId::VideoSchedulerDecodedFramesPerTick
        }
        "video.scheduler.catch_up_budget_ms" => {
            PlayerRuntimeSettingId::VideoSchedulerCatchUpBudgetMs
        }
        "video.scheduler.present_queue_min_frames" => {
            PlayerRuntimeSettingId::VideoSchedulerPresentQueueMinFrames
        }
        "video.scheduler.present_queue_target_frames" => {
            PlayerRuntimeSettingId::VideoSchedulerPresentQueueTargetFrames
        }
        "video.scheduler.decode_ahead_target_ms" => {
            PlayerRuntimeSettingId::VideoSchedulerDecodeAheadTargetMs
        }
        "video.scheduler.surface_free_slots_min" => {
            PlayerRuntimeSettingId::VideoSchedulerSurfaceFreeSlotsMin
        }
        "video.scheduler.surface_free_slots_target" => {
            PlayerRuntimeSettingId::VideoSchedulerSurfaceFreeSlotsTarget
        }
        _ => return None,
    };

    Some(runtime_id)
}

fn setting_ids_from_diff(diff: &SettingsDiff) -> Vec<SettingId> {
    diff.changes()
        .iter()
        .map(|change| change.id.clone())
        .collect()
}

fn push_unique_setting_id(ids: &mut Vec<SettingId>, id: SettingId) {
    if !ids.iter().any(|existing| existing == &id) {
        ids.push(id);
    }
}

fn push_unique_setting_route(routes: &mut Vec<SettingRouteId>, route: SettingRouteId) {
    if !routes.iter().any(|existing| existing == &route) {
        routes.push(route);
    }
}

fn settings_error_from_display(error: impl std::fmt::Display) -> SettingsError {
    SettingsError::access_failed(error.to_string())
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;
    use std::fs;
    use std::rc::Rc;
    use std::time::{SystemTime, UNIX_EPOCH};

    use render_core::{
        ColorPipelineSettings, HdrToSdrSettings, RenderLiveSettingId, ToneMappingMode,
    };
    use settings_core::{
        ApplyFinalState, ApplyRouteResult, PersistRequest, SettingValue, SettingsController,
    };

    use super::*;

    #[test]
    fn validation_failure_blocks_persist_and_runtime_apply() {
        let registry = app_config_registry().expect("registry builds");
        let mut controller = SettingsController::new(AppConfig::default(), registry);
        controller
            .set_value(
                SettingId::from("render.hdr_to_sdr.hdr_reference_peak_nits"),
                SettingValue::Float(90.0),
            )
            .expect("descriptor-level value is valid");

        let state = Rc::new(RefCell::new(CallState::default()));
        let mut delegate = RecordingDelegate::new(state.clone(), temp_config_path());

        let report = controller
            .apply(&mut delegate)
            .expect("apply returns report");

        assert_eq!(report.final_state, ApplyFinalState::ValidationFailed);
        assert_eq!(state.borrow().calls, vec!["validate"]);
        assert!(!delegate.path().exists());
    }

    #[test]
    fn controller_persists_before_runtime_apply() {
        let registry = app_config_registry().expect("registry builds");
        let mut controller = SettingsController::new(AppConfig::default(), registry);
        controller
            .set_value(
                SettingId::from("ui.language"),
                SettingValue::Text("en".into()),
            )
            .expect("draft edit succeeds");

        let state = Rc::new(RefCell::new(CallState::default()));
        let path = temp_config_path();
        let mut delegate = RecordingDelegate::new(state.clone(), path.clone());

        let report = controller.apply(&mut delegate).expect("apply succeeds");

        assert_eq!(report.final_state, ApplyFinalState::FullyApplied);
        assert_eq!(state.borrow().calls, vec!["validate", "persist", "apply"]);
        assert!(state.borrow().persisted_file_seen_by_apply);

        let saved = fs::read_to_string(&path).expect("saved config exists");
        assert!(saved.contains("language = \"en\""));
        remove_file_if_exists(&path);
    }

    #[test]
    fn render_live_mapping_matches_existing_app_egui_behavior() {
        let mut config = AppConfig::default();
        config.render.color_adjustment.brightness = 0.1;
        config.render.color_adjustment.contrast = 1.2;
        config.render.color_adjustment.saturation = 0.9;
        config.render.color_adjustment.exposure = -0.25;
        config.render.color_adjustment.rgb_gain = vec![1.0, 0.95, 1.05];
        config.render.color_adjustment.rgb_offset = vec![0.01, -0.02, 0.03];
        config.render.hdr_to_sdr.enabled = true;
        config.render.hdr_to_sdr.sdr_reference_white_nits = 120.0;
        config.render.hdr_to_sdr.hdr_reference_peak_nits = 1_200.0;

        let mapped = render_live_settings_from_config(&config).expect("render mapping succeeds");

        assert_eq!(
            mapped.color_pipeline,
            ColorPipelineSettings {
                adjustment: ColorAdjustment {
                    brightness: 0.1,
                    contrast: 1.2,
                    saturation: 0.9,
                    exposure: -0.25,
                    rgb_gain: [1.0, 0.95, 1.05],
                    rgb_offset: [0.01, -0.02, 0.03],
                },
                tone_mapping: ToneMappingMode::Off,
                swapchain_transfer: SwapchainTransferMode::PreserveCurrentUnorm,
            }
        );
        assert_eq!(
            mapped.hdr_to_sdr,
            HdrToSdrSettings {
                enabled: true,
                operator: HdrToneMappingOperator::Bt2446C,
                output_mode: HdrOutputMode::SdrBt709Only,
                sdr_reference_white_nits: 120.0,
                hdr_reference_peak_nits: 1_200.0,
            }
        );
    }

    #[test]
    fn route_diff_groups_affected_settings_by_typed_owner_routes() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.ui.language = "en".into();
        current.render.color_adjustment.brightness = 0.2;
        current.render.profile = RenderProfile::OpenGles;
        current.video.scheduler.demux_packets_per_tick += 1;
        current.network.read_ahead_mb += 1;
        current.youtube.enabled = !current.youtube.enabled;

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");

        assert_eq!(plan.preview_routes.len(), 1);
        assert_eq!(plan.preview_routes[0].route, AppRuntimeRoute::RenderPreview);
        assert_eq!(
            plan.preview_routes[0].affected_settings,
            vec![SettingId::from("render.color_adjustment.brightness")]
        );

        let committed_routes: Vec<AppRuntimeRoute> = plan
            .committed_routes
            .iter()
            .map(|route| route.route)
            .collect();
        assert_eq!(
            committed_routes,
            vec![
                AppRuntimeRoute::Ui,
                AppRuntimeRoute::RenderPreview,
                AppRuntimeRoute::RenderCommitted,
                AppRuntimeRoute::Player,
                AppRuntimeRoute::MediaService,
            ]
        );

        let player_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::Player)
            .expect("player route exists");
        assert_eq!(
            player_route.groups,
            vec![AppRuntimeRouteGroupUpdate {
                group: AppRuntimeRouteGroup::PlayerTickConfig,
                affected_settings: vec![SettingId::from("video.scheduler.demux_packets_per_tick")],
            }]
        );

        let media_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::MediaService)
            .expect("media route exists");
        assert_eq!(
            media_route.groups,
            vec![
                AppRuntimeRouteGroupUpdate {
                    group: AppRuntimeRouteGroup::MediaNetwork,
                    affected_settings: vec![SettingId::from("network.read_ahead_mb")],
                },
                AppRuntimeRouteGroupUpdate {
                    group: AppRuntimeRouteGroup::MediaYoutube,
                    affected_settings: vec![SettingId::from("youtube.enabled")],
                },
            ]
        );
    }

    #[test]
    fn audio_output_device_route_uses_owner_payload_not_deferred_boundary() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.audio.output_device = "cpal-0.15-name:USB%20DAC".to_string();

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");

        let player_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::Player)
            .expect("player route exists");
        let RuntimeCommittedUpdate::Player(update) = &player_route.update else {
            panic!("audio.output_device должен попасть в player route update");
        };

        assert_eq!(
            player_route.groups,
            vec![AppRuntimeRouteGroupUpdate {
                group: AppRuntimeRouteGroup::PlayerAudioOutputDevice,
                affected_settings: vec![SettingId::from("audio.output_device")],
            }]
        );
        assert_eq!(
            update.audio_output_device_id.as_deref(),
            Some("cpal-0.15-name:USB%20DAC")
        );
        assert!(update.deferred_boundary_settings.is_empty());
    }

    #[test]
    fn preferred_backend_route_requests_pipeline_rebuild_not_deferred_boundary() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.video.preferred_backend = rustiplayer_config::VideoBackendPreference::Hardware;

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");

        let player_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::Player)
            .expect("player route exists");
        let RuntimeCommittedUpdate::Player(update) = &player_route.update else {
            panic!("video.preferred_backend должен попасть в player route update");
        };

        assert_eq!(
            player_route.groups,
            vec![AppRuntimeRouteGroupUpdate {
                group: AppRuntimeRouteGroup::PlayerVideoBackend,
                affected_settings: vec![SettingId::from("video.preferred_backend")],
            }]
        );
        assert_eq!(
            update
                .player_core
                .video_backend
                .as_ref()
                .expect("video backend update expected")
                .affected_settings,
            vec![PlayerRuntimeSettingId::VideoPreferredBackend]
        );
        assert!(update.deferred_boundary_settings.is_empty());
    }

    #[test]
    fn decoder_ready_queue_route_updates_decoder_and_tick_capacity() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.video.decoder_ready_queue_frames = 3;

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");

        let player_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::Player)
            .expect("player route exists");
        let RuntimeCommittedUpdate::Player(update) = &player_route.update else {
            panic!("decoder ready queue должен попасть в player route update");
        };

        assert_eq!(
            player_route.groups,
            vec![AppRuntimeRouteGroupUpdate {
                group: AppRuntimeRouteGroup::PlayerDecoderThreadConfig,
                affected_settings: vec![SettingId::from("video.decoder_ready_queue_frames")],
            }]
        );
        assert_eq!(
            update
                .player_core
                .decoder_thread_config
                .as_ref()
                .expect("decoder-thread update expected")
                .decoder_thread_config
                .decoder_ready_queue_frames,
            3
        );
        assert_eq!(
            update
                .player_core
                .tick_config
                .as_ref()
                .expect("tick update expected")
                .tick_config
                .decoder_ready_queue_frames,
            3
        );
        assert!(update.deferred_boundary_settings.is_empty());
    }

    #[test]
    fn route_reports_preserve_affected_setting_ids_and_debt_is_not_success() {
        let report = AppRouteApplyReport {
            route: AppRuntimeRoute::MediaService,
            source_routes: vec![SettingRouteId::from(NETWORK_ROUTE_ID)],
            result: AppRouteApplyResult::DeferredTechnicalDebt {
                message: "media service owner boundary is not wired yet".into(),
            },
            mechanism: ApplyMechanism::DeferredTechnicalDebt,
            affected_settings: vec![SettingId::from("network.read_ahead_mb")],
            groups: vec![AppRouteGroupReport {
                group: AppRuntimeRouteGroup::MediaNetwork,
                result: AppRouteApplyResult::DeferredTechnicalDebt {
                    message: "media service owner boundary is not wired yet".into(),
                },
                affected_settings: vec![SettingId::from("network.read_ahead_mb")],
            }],
        };

        assert!(!report.result.is_success());
        assert_eq!(
            report.groups[0].affected_settings,
            vec![SettingId::from("network.read_ahead_mb")]
        );

        let core_report = report.into_core_report();
        assert_eq!(core_report.route, SettingRouteId::from(NETWORK_ROUTE_ID));
        assert_eq!(core_report.mechanism, ApplyMechanism::DeferredTechnicalDebt);
        assert!(matches!(
            core_report.result,
            ApplyRouteResult::Failed { .. }
        ));
        assert_eq!(
            core_report.affected_settings,
            vec![SettingId::from("network.read_ahead_mb")]
        );
    }

    #[test]
    fn media_service_route_groups_without_service_crate_dependencies() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.network.prefetch_chunk_mb += 1;
        current.youtube.resolve_timeout_ms += 100;

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");
        let media_route = plan
            .committed_routes
            .iter()
            .find(|route| route.route == AppRuntimeRoute::MediaService)
            .expect("media route exists");

        assert_eq!(
            media_route.source_routes,
            vec![
                SettingRouteId::from(NETWORK_ROUTE_ID),
                SettingRouteId::from(YOUTUBE_ROUTE_ID),
            ]
        );
        assert!(matches!(
            media_route.update,
            RuntimeCommittedUpdate::MediaService(_)
        ));
    }

    #[test]
    fn render_preview_route_uses_render_core_field_diff() {
        let registry = app_config_registry().expect("registry builds");
        let mut current = AppConfig::default();
        current.render.color_adjustment.brightness = 0.15;
        current.render.hdr_to_sdr.sdr_reference_white_nits = 110.0;

        let diff = registry
            .diff(&AppConfig::default(), &current)
            .expect("diff succeeds");
        let plan = runtime_route_plan_from_diff(&registry, &AppConfig::default(), &current, &diff)
            .expect("route plan builds");

        let RuntimePreviewUpdate::Render(update) = &plan.preview_routes[0].update;
        assert_eq!(
            update.live_settings.changed_fields,
            vec![
                RenderLiveSettingId::ColorAdjustmentBrightness,
                RenderLiveSettingId::HdrToSdrSdrReferenceWhiteNits,
            ]
        );
    }

    #[derive(Debug, Default)]
    struct CallState {
        calls: Vec<&'static str>,
        persisted_file_seen_by_apply: bool,
    }

    struct RecordingDelegate {
        state: Rc<RefCell<CallState>>,
        store: AppConfigStore,
    }

    impl RecordingDelegate {
        fn new(state: Rc<RefCell<CallState>>, path: PathBuf) -> Self {
            Self {
                state,
                store: AppConfigStore::new(path),
            }
        }

        fn path(&self) -> &Path {
            self.store.path()
        }
    }

    impl SettingsValidator<AppConfig> for RecordingDelegate {
        fn validate(
            &mut self,
            request: ValidationRequest<'_, AppConfig>,
        ) -> SettingsResult<ValidationReport> {
            self.state.borrow_mut().calls.push("validate");
            AppConfigValidator.validate(request)
        }
    }

    impl SettingsPersister<AppConfig> for RecordingDelegate {
        fn persist(
            &mut self,
            request: PersistRequest<'_, AppConfig>,
        ) -> SettingsResult<PersistReport> {
            self.state.borrow_mut().calls.push("persist");
            self.store.persist(request)
        }
    }

    impl CommittedSettingsApplier<AppConfig> for RecordingDelegate {
        fn apply_committed(
            &mut self,
            request: CommittedApplyRequest<'_, AppConfig>,
        ) -> SettingsResult<Vec<ApplyRouteReport>> {
            self.state.borrow_mut().calls.push("apply");
            self.state.borrow_mut().persisted_file_seen_by_apply = self.path().exists();

            Ok(request
                .route_updates
                .iter()
                .map(|update| {
                    ApplyRouteReport::applied(
                        update.route.clone(),
                        update.affected_settings.clone(),
                    )
                })
                .collect())
        }
    }

    fn temp_config_path() -> PathBuf {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time after epoch")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "rustiplayer-settings-test-{}-{timestamp}.toml",
            std::process::id()
        ))
    }

    fn remove_file_if_exists(path: &Path) {
        match fs::remove_file(path) {
            Ok(()) | Err(_) => {}
        }
    }
}
