use fastiplayer_config::AppConfig;

use super::{
    AppRuntimeRoute, MediaServiceRuntimeSettingsUpdate, RouteInput, RuntimeCommittedRoute,
    RuntimeCommittedUpdate,
};

/// Route id generated by metadata for provider-neutral web-media policy.
pub const WEB_MEDIA_ROUTE_ID: &str = "web_media";

/// Собирает атомарный snapshot всех трёх media-service policy owners.
pub(super) fn committed_route(current: &AppConfig, input: RouteInput) -> RuntimeCommittedRoute {
    let groups = input.groups();

    RuntimeCommittedRoute {
        route: AppRuntimeRoute::MediaService,
        source_routes: input.source_routes,
        affected_settings: input.affected_settings,
        groups,
        update: RuntimeCommittedUpdate::MediaService(MediaServiceRuntimeSettingsUpdate {
            network: current.network.clone(),
            web_media: current.web_media.clone(),
            yt_dlp: current.yt_dlp.clone(),
        }),
    }
}
