[package]
name = "service-youtube"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "service_youtube"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
capability-core = { workspace = true }
codec-core = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { workspace = true }
serde_json = "1.0"
rustiplayer-config = { workspace = true }
source-core = { workspace = true }
tracing = { workspace = true }
webm-demux = { path = "../webm-demux" }

[dev-dependencies]
media-core = { workspace = true }
