[package]
name = "service-direct-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "service_direct_media"
path = "src/lib.rs"

[dependencies]
demux-api = { workspace = true }
source-core = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
web-media-transport-api = { workspace = true }

[dev-dependencies]
symphonia-demux = { workspace = true }
