[package]
name = "service-direct-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "service_direct_media"
path = "src/lib.rs"

[dependencies]
media-prefetch = { workspace = true }
rustiplayer-config = { workspace = true }
source-core = { workspace = true }
symphonia-demux = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
