[package]
name = "render-wgpu-video"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
codec-core = { workspace = true }
render-core = { workspace = true }
video-core = { workspace = true }
video-backend-api = { workspace = true }
wgpu.workspace = true
tracing.workspace = true
video-frame-contract.workspace = true
ash = "0.38"
bytemuck = "1.25"
nix = { version = "0.29", features = ["fs"] }
wgpu-types = "29"

[dev-dependencies]
naga = { version = "29", features = ["wgsl-in"] }
