[package]
name = "rustiplayer-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "rustiplayer_settings"
path = "src/lib.rs"

[dependencies]
player-core.workspace = true
render-core.workspace = true
rustiplayer-config.workspace = true
settings-core.workspace = true
