[package]
name = "symphonia-demux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
symphonia = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
media-core = { workspace = true }
demux-api = { workspace = true }
codec-core = { workspace = true }
source-core = { workspace = true }
symphonia-format-isomp4.workspace = true

[dev-dependencies]
audio = { workspace = true }
