[package]
name = "smooth-streaming-fmp4"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
smooth-streaming-manifest-core.workspace = true
symphonia-format-isomp4.workspace = true
thiserror.workspace = true

[dev-dependencies]
bounded-xml-reader.workspace = true
