[package]
name = "player-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "player_core"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
audio-core = { workspace = true }
bytes = { workspace = true }
capability-core = { workspace = true }
codec-core = { workspace = true }
crossbeam-channel = { workspace = true }
media-core = { workspace = true }
rustiplayer-config = { workspace = true }
tracing = { workspace = true }
video-core = { path = "../video-core" }

[dev-dependencies]
render-core = { workspace = true }
