[package]
name = "video-backend-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
video-core.workspace = true

[dev-dependencies]
codec-core.workspace = true
media-core.workspace = true
video-frame-contract.workspace = true
