[package]
name = "web-media-ftp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
source-core.workspace = true
web-media-transport-api.workspace = true

[dev-dependencies]
rustiplayer-config.workspace = true
web-media-core.workspace = true
